version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - "PGDATA=/var/lib/postgresql/data"
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_HOST=${POSTGRES_HOST}
  web:
    build: .
    environment:
      - RAILS_ENV=${RAILS_ENV}
    command: bundle exec rails s -p 3000 -b '0.0.0.0' -e ${RAILS_ENV}
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
    # tty: true
    # stdin_open: true
