# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.3-node-browsers
        environment:
          - PG_HOST=localhost
          - PG_USER=ubuntu
          - RAILS_ENV=test
          - RACK_ENV=test
      - image: circleci/postgres:9.4
        environment:
          - POSTGRES_USER=ubuntu
          - POSTGRES_DB=db_name
    working_directory: ~/repo

    steps:
      - checkout
      - run:
          command: "[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow"

      # Download and cache dependencies
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          # - v1-dependencies-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          # - v1-dependencies-

      - run:
          name: Install dependencies
          command: |
            sudo apt-get install cmake python-pip yamllint python3-pkg-resources
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
          name: Load DB
          command: bundle exec rake db:schema:load
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"

      # run tests!
      - run:
          name: Rubocop
          command: |
            mkdir /tmp/test-results
            bundle exec rubocop

      - run:
          name: RSpec
          command: bundle exec rspec
          environment:
            DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"

      - run:
          name: YAML lint
          command: yamllint config/locales/

      # collect reports
      - store_test_results:
          path: /tmp/test-results

      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

      # - run:
      #    name: Post (pronto)
      #    command: 'if [ -n "${CI_PULL_REQUEST}" ]; then bundle exec pronto run -f github_pr -c origin/master; fi'
